/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant;

import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class SearchFrame extends javax.swing.JFrame {

    /**
     * Creates new form SearchFrame
     */
    public SearchFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PasswordLogin = new javax.swing.JPasswordField();
        UsernameLogin = new javax.swing.JTextField();
        EnterLogin = new javax.swing.JButton();
        SignUp = new javax.swing.JLabel();
        CloseButton = new javax.swing.JLabel();
        ResDef = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PasswordLogin.setText("jPasswordField1");
        getContentPane().add(PasswordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 4, -1, -1));

        UsernameLogin.setText("Username/Email");
        UsernameLogin.setAlignmentY(1.0F);
        UsernameLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameLoginActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 110, 20));

        EnterLogin.setBackground(new java.awt.Color(255, 204, 51));
        EnterLogin.setText("Enter");
        EnterLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterLoginActionPerformed(evt);
            }
        });
        getContentPane().add(EnterLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 4, 80, 20));

        SignUp.setForeground(new java.awt.Color(255, 204, 0));
        SignUp.setText("Click Here to Sign-Up for Free");
        getContentPane().add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 5, 200, -1));

        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ResTest/closeButton.png"))); // NOI18N
        CloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonMouseClicked(evt);
            }
        });
        getContentPane().add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 5, -1, -1));

        ResDef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ResTest/UtensilDefault1.png"))); // NOI18N
        ResDef.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResDef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResDefMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ResDefMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ResDefMouseExited(evt);
            }
        });
        getContentPane().add(ResDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 137, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ResTest/FinalBack.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameLoginActionPerformed

    private void EnterLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterLoginActionPerformed

    private void ResDefMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResDefMouseEntered
      ImageIcon II = new ImageIcon(getClass().getResource("/ResTest/UtensilHover1.png"));
       ResDef.setIcon(II);    
// TODO add your handling code here:
    }//GEN-LAST:event_ResDefMouseEntered

    private void ResDefMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResDefMouseExited
       ImageIcon II = new ImageIcon(getClass().getResource("/ResTest/UtensilDefault1.png"));
       ResDef.setIcon(II);
        // TODO add your handling code here:
    }//GEN-LAST:event_ResDefMouseExited

    private void ResDefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResDefMouseClicked
            ActionFrame Test = new ActionFrame();
             Test.setVisible(true); 
// TODO add your handling code here:
    }//GEN-LAST:event_ResDefMouseClicked

    private void CloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseClicked
     System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_CloseButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CloseButton;
    private javax.swing.JButton EnterLogin;
    private javax.swing.JPasswordField PasswordLogin;
    private javax.swing.JLabel ResDef;
    private javax.swing.JLabel SignUp;
    private javax.swing.JTextField UsernameLogin;
    // End of variables declaration//GEN-END:variables
}
